<a href="https://colab.research.google.com/github/Omdena-Bhutan/starter-assignment-sonamyanchen21-max/blob/main/Numpy_2D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
# import numpy as np

In [7]:
a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [19]:
import numpy as np
A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [20]:
A.ndim

2

In [21]:
A.shape

(3, 3)

In [22]:
A.size

9

In [24]:
new_var = A[1, 2]
new_var

np.int64(23)

In [25]:
A[1][2]

np.int64(23)

In [26]:
A[0][0]

np.int64(11)

In [27]:
A[0][0:2]

array([11, 12])

In [28]:
A[0:2, 2]

array([13, 23])

In [29]:
X = np.array([[1, 0], [0, 1]])
X

array([[1, 0],
       [0, 1]])

In [30]:
Y = np.array([[2, 1], [1, 2]])
Y

array([[2, 1],
       [1, 2]])

In [31]:
Z = X + Y
Z

array([[3, 1],
       [1, 3]])

In [35]:
z = 2 * Y
z

array([[4, 2],
       [2, 4]])

In [33]:
Y = np.array([[2, 1], [1, 2]])
Y

array([[2, 1],
       [1, 2]])

In [36]:
Z = X * Y
Z

array([[2, 0],
       [0, 2]])

In [37]:
A = np.array([[0, 1, 1], [1, 0, 1]])
A

array([[0, 1, 1],
       [1, 0, 1]])

In [38]:
B = np.array([[1, 1], [1, 1], [-1, 1]])
B

array([[ 1,  1],
       [ 1,  1],
       [-1,  1]])

In [39]:
Z = np.dot(A,B)
Z

array([[0, 2],
       [0, 2]])

In [40]:
np.sin(Z)

array([[0.        , 0.90929743],
       [0.        , 0.90929743]])

In [41]:
C = np.array([[1,1],[2,2],[3,3]])
C

array([[1, 1],
       [2, 2],
       [3, 3]])

In [42]:
C.T

array([[1, 2, 3],
       [1, 2, 3]])

In [43]:
a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
A = np.array(a)
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [44]:
A.size

12

In [45]:
A.shape

(3, 4)

In [46]:
A[0][0:2]

array([1, 2])

In [47]:
B = np.array([[0, 1], [1, 0], [1, 1], [-1, 0]])
X = np.dot(A,B)
X


array([[ 1,  4],
       [ 5, 12],
       [ 9, 20]])